// GENERATED by scripts/build-images.py from photos-src/gallery.json. Do not edit by hand.
// Each slot is a photo Mercedes can replace at /upload; full/thumb are the static fallbacks;
// lightbox is the id of its enlarged view in index.html (functions/index.js rewrites its caption).
export const SLOTS = {
  "hero": { label: "Big photo", full: "/assets/selfie.webp", thumb: "/assets/selfie.webp", lightbox: "photo-hero" },
  "photo-1": { label: "Small photo 1", full: "/assets/gallery/portrait.webp", thumb: "/assets/gallery/portrait-thumb.webp", lightbox: "photo-portrait" },
  "photo-2": { label: "Small photo 2", full: "/assets/gallery/lawn.webp", thumb: "/assets/gallery/lawn-thumb.webp", lightbox: "photo-lawn" },
  "photo-3": { label: "Small photo 3", full: "/assets/gallery/arch.webp", thumb: "/assets/gallery/arch-thumb.webp", lightbox: "photo-arch" },
  "photo-4": { label: "Small photo 4", full: "/assets/gallery/street.webp", thumb: "/assets/gallery/street-thumb.webp", lightbox: "photo-street" },
  "photo-5": { label: "Small photo 5", full: "/assets/gallery/stripes.webp", thumb: "/assets/gallery/stripes-thumb.webp", lightbox: "photo-stripes" },
};
